#!/bin/bash

function __DefParam() {
	POSTDATA["user"]="$1"
	POSTDATA["passwd"]="$2"
	POSTDATA["email"]="$3"
}

goal "Account Registration"
{
	declare -A POSTDATA=(
		["action"]="register"
		["lang"]="$RLANG"
	)

	goal "Empty password"
	{
		__DefParam "$ACCOUNT" "" "$EMAIL"
		. ./tests/assert_jfail
		goalend
	}

	goal "Empty username"
	{
		__DefParam "" "$PASSWD" "$EMAIL"
		. ./tests/assert_jfail
		goalend
	}

	goal "Empty email"
	{
		__DefParam "$ACCOUNT" "$PASSWD" ""
		. ./tests/assert_jfail
		goalend
	}

	goal "Password: aaa"
	{
		__DefParam "$ACCOUNT" "aaa" "$EMAIL"
		. ./tests/assert_jfail
		goalend
	}

	goal "Password: 12345678"
	{
		__DefParam "$ACCOUNT" "12345678" "$EMAIL"
		. ./tests/assert_jfail
		goalend
	}

	goal "Password: 123456789aa"
	{
		__DefParam "$ACCOUNT" "123456789aa" "$EMAIL"
		. ./tests/assert_jfail
		goalend
	}

	goal "Email: invalid_email"
	{
		__DefParam "$ACCOUNT" "$PASSWD" "invalid_email"
		. ./tests/assert_jfail
		goalend
	}

	goal "Email: invalid@email"
	{
		__DefParam "$ACCOUNT" "$PASSWD" "invalid@email"
		. ./tests/assert_jfail
		goalend
	}

	goal "Email: invalid@com.@mail.email"
	{
		__DefParam "$ACCOUNT" "$PASSWD" "invalid@com.@mail.email"
		. ./tests/assert_jfail
		goalend
	}

	goal "Providing valid data"
	{
		__DefParam "$ACCOUNT" "$PASSWD" "$EMAIL"
		. ./tests/assert_jsuccess
		goalend
	}

	goal "Register again"
	{
		. ./tests/assert_jfail
		goalend
	}

	goal "Register again with different cases"
	{
		__DefParam "$ACCOUNT_2" "$PASSWD" "$EMAIL"
		. ./tests/assert_jfail
		goalend
	}

	goalend
}
