#!/bin/bash

goal "Account Registration"
{
    declare -A POSTDATA=(
        ["action"]="register"
        ["user"]="$ACCOUNT"
        ["passwd"]="$PASSWD"
        ["lang"]="$RLANG"
    )

    . ./tests/assert_jsuccess
}
