#!/bin/bash

SEND_COOKIE=true

goal "Account Login ( using \"$ACCOUNT_2\" as they should be the same )"
{
	declare -A POSTDATA=(
		["action"]="login"
		["user"]="$ACCOUNT_2"
		["passwd"]="$PASSWD"
		["lang"]="$RLANG"
	)

	goal "Send login request"
	{
		wget -qO- "http://127.0.0.1:$SERVER_PORT/" \
			--save-cookies $COOKIE \
			--keep-session-cookies \
			--post-data "$( compost POSTDATA )" > $TempFile
		exitOk $? "Cannot download the required file"
	}

	goal "Checking cookie sid"
	{
		grep -q sid $COOKIE
		exitOk $? "sid is not defined"
	}

	goalend
}

goal "Account Login ( already logged in )"
{
	. ./tests/assert_jfail
	goalend
}

goal "Session check"
{
	declare -A POSTDATA=(
		["action"]="session-valid"
		["lang"]="$RLANG"
	)

	. ./tests/assert_jsuccess
	goalend
}
