#!/bin/bash

SEND_COOKIE=true

goal "Account Logout"
{
	declare -A POSTDATA=(
		["action"]="logout"
		["lang"]="$RLANG"
	)

	. ./tests/assert_jsuccess

	goalend
}

goal "Session check"
{
	declare -A POSTDATA=(
		["action"]="session-valid"
		["lang"]="$RLANG"
	)

	. ./tests/assert_jfail
	goalend
}
