#!/bin/bash

goal "Upload script"
{
    declare -A POSTDATA=(
        ["uuid"]="$UUID"
        ["action"]="upload"
        ["data"]="$SCRIPT_DATA"
        ["name"]="toast"
        ["desc"]="Example Description"
        ["secret"]="What is my pet name"
        ["zone"]="小説家になろう"
        ["type"]="ja"
    )

    . ./tests/assert_token_access
}
