#!/bin/bash
SEND_COOKIE=true
NEW_PASS="GGGGuhecGGGG"

goal "Account Change Password"

. ./tests/002_login
echo ok

goal "with wrong current password"

declare -A POSTDATA=(
    ["action"]="passwd"
    ["curr"]="$NEW_PASS"
    ["new"]="1111111"
    ["lang"]="$RLANG"
)

. ./tests/assert_jfail
echo ok

goal "with good current password"
declare -A POSTDATA=(
    ["action"]="passwd"
    ["curr"]="$PASSWD"
    ["new"]="$NEW_PASS"
    ["lang"]="$RLANG"
)

. ./tests/assert_jsuccess
echo ok

. ./tests/003_logout
echo ok

goal "Login with old password"
declare -A POSTDATA=(
    ["action"]="login"
    ["user"]="$ACCOUNT"
    ["passwd"]="$PASSWD"
    ["lang"]="$RLANG"
)

. ./tests/assert_jfail
echo ok

goal "Login with new password"
declare -A POSTDATA=(
    ["action"]="login"
    ["user"]="$ACCOUNT"
    ["passwd"]="$NEW_PASS"
    ["lang"]="$RLANG"
)

wget -qO- "http://127.0.0.1:$SERVER_PORT/" \
    --save-cookies $COOKIE \
    --keep-session-cookies \
    --post-data "$( compost POSTDATA )" > $TempFile
exitOk $? "Cannot download the required file"

grep -q sid $COOKIE
exitOk $? "sid is not defined"

echo ok

goal "Change the password back"
declare -A POSTDATA=(
    ["action"]="passwd"
    ["curr"]="$NEW_PASS"
    ["new"]="$PASSWD"
    ["lang"]="$RLANG"
)

. ./tests/assert_jsuccess
echo ok

. ./tests/003_logout
