#!/bin/bash

goal "Publish script"
{
    declare -A POSTDATA=(
        ["action"]="publish"
        ["uuid"]="$UUID"
        ["public"]="1"
        ["lang"]="$RLANG"
    )

    . ./tests/assert_token_access

    goal "Checking published state"
    {
        declare -A POSTDATA=(
            ["action"]="list"
            ["lang"]="$RLANG"
        )

        . ./tests/assert_jsuccess

        grep -q "$UUID" $TempFile
        exitOk $? "Published script was not listed"
    }

    goal "Unpublish script"
    {
        declare -A POSTDATA=(
            ["action"]="publish"
            ["uuid"]="$UUID"
            ["public"]="0"
            ["lang"]="$RLANG"
        )

        . ./tests/assert_token_access

        grep -vq "$UUID" $TempFile
        exitOk $? "Published script was listed"
    }
}
