#!/bin/bash

goal "Sending Request"
{
    if $SEND_COOKIE; then
        wget -qO- "http://127.0.0.1:$SERVER_PORT/" \
            --load-cookies $COOKIE \
            --post-data "$( compost POSTDATA )" > $TempFile
    else
        wget -qO- "http://127.0.0.1:$SERVER_PORT/" --post-data "$( compost POSTDATA )" > $TempFile
    fi

    exitOk $? "Cannot download the required file"
}

goal "Action should fail"
{
    grep -q "\"status\":false" $TempFile
    exitOk $? "Unsuccessful status"
}
