#!/bash/bash

declare -A POSTDATA=(
	["uuid"]="$UUID"
	["action"]="upload"
	["name"]="Script 003 中文"
	["desc"]="Description of script 002 中文"
	["encrypted"]="0"
	["zone"]="Zone 2"
	["type"]="Type B"
	["scope"]="book"
	["compat"]="1.0.0t"
	["data"]="
<xml>
	<test2>MMMMM</test2>
	<test>DDDDDDDDDD</test>
</xml>
"
)
