#!/bash/bash

declare -A POSTDATA=(
	["uuid"]="$UUID"
	["action"]="upload"
	["name"]="Script 004"
	["desc"]="Description of script 003 文"
	["encrypted"]="0"
	["zone"]="隨機網文"
	["type"]="Type A"
	["scope"]="book"
	["compat"]="1.0.0t"
	["data"]="
<xml>
	<test>小説家になろう</test>
</xml>
"
)
