#!/bash/bash

declare -A POSTDATA=(
	["uuid"]="$UUID"
	["action"]="upload"
	["name"]="TEST012 ( Encrypted )"
	["desc"]="Example Description"
	["encrypted"]="1"
	["zone"]="小説家になろう"
	["type"]="Type C"
	["data"]="
<xml>
	<test>Test test</test>
</xml>
"
)
