#!/bash/bash

declare -A POSTDATA=(
	["uuid"]="$UUID"
	["action"]="upload"
	["name"]="TEST012"
	["desc"]="Example Description"
	["encrypted"]="0"
	["zone"]="小説家になろう"
	["type"]="Type C"
	["scope"]="book"
	["compat"]="1.0.0t"
	["data"]="
<xml>
	<test>Test test</test>
</xml>
"
)
