#!/bin/bash

echo "Applying database settings"
sed -i "s/localhost\/wcache/192.168.80.100\/wcache/g" ./wen10srv/config/db.js

echo "Changing the Log Level"

sed -i "s/Dragonfly.defaultSphere.\+/Dragonfly.defaultSphere = 999;/g" ./index.js
echo -n "Server LogLevel as at: "
grep "Dragonfly.defaultSphere" ./index.js

node ./tests/secscripts/rmTestCollection.js
stopTest $?
