module.exports = [
	"password", "marlboro", "danielle", "asdfasdf", "redskins", "airborne", "elephant"
	, "victoria", "cocacola", "baseball", "football", "internet", "godzilla", "explorer"
	, "williams", "lifehack", "christin", "butthead", "december", "mountain", "dickhead"
	, "platinum", "brooklyn", "jennifer", "mercedes", "benjamin", "superman", "Rush2112"
	, "jonathan", "garfield", "shithead", "trustno1", "redwings", "startrek", "michigan"
	, "87654321", "nicholas", "metallic", "scorpion", "jordan23", "bigdaddy", "liverpoo"
	, "guinness", "qwertyui", "michelle", "Midnight", "einstein", "sunshine", "colorado"
	, "champion", "creative", "passport", "bollocks", "snowball", "rolltide", "marshall"
	, "security", "bulldogs", "1qaz2wsx", "veronica", "elizabet", "starwars", "caroline"
	, "abcd1234", "wolfpacks", "darkness", "lawrence", "snickers", "remember", "american"
	, "courtney", "wildcats", "westside", "stingray", "carolina", "wolverin", "liverpool"
	, "computer", "mitchell", "mistress", "hendrick", "patricia", "1q2w3e4r", "stargate"
	, "password1", "corvette", "semperfi", "brittany", "kimberly", "spiderman", "patriots"
	, "slipknot", "paradise", "freeuser", "scotland", "kawasaki", "lasvegas", "panthers"
	, "passw0rd", "maryjane", "pussycat", "anderson", "alexande", "princess", "loverboy"
	, "swordfis", "wolfgang", "infinity", "hercules", "pavilion", "wrangler", "zeppelin"
	, "sterling", "charlie1", "q1w2e3r4", "devildog", "12341234", "bluebird", "harrison"
	, "asdf1234", "enterprise", "blizzard", "iloveyou", "precious", "engineer", "basketball"
	, "valentine", "987654321", "1234qwer", "hamilton", "icecream", "pleasure", "marathon"
	, "atlantis", "predator", "hollywood", "hello123", "campbell", "rockstar", "mongoose"
	, "clifford", "sherlock", "dietcoke", "ultimate", "maverick", "microsoft", "florence"
	, "alexandra", "stardust", "frontier", "showtime", "mustangs", "napoleon", "motorola"
	, "robinson", "columbia", "stranger", "samantha", "hongkong", "kingkong", "anything"
	, "thompson", "steelers", "fernando", "dingdong", "cooldude", "a1b2c3d4", "peterpan"
	, "monopoly", "1234abcd", "candyman", "eternity", "chevrolete", "whatever", "1qazxsw2"
	, "santiago", "maryland", "12344321", "catherin", "starship", "angelica", "front242"
	, "qwer1234", "technics", "piercing", "robotech", "zaq12wsx", "universe", "mechanic"
	, "spectrum", "handsome", "keystone", "something", "kingston", "luckydog", "pa55word"
	, "testing1", "halflife", "godfather", "manchester", "happy123", "anaconda", "gotohell"
	, "monalisa", "james007", "hardcore", "paaswort", "lionking", "poseidon", "thunderbird"
	, "handyman", "19691969", "sandwich", "casanova", "1a2b3c4d", "sebastian", "meowmeow"
	, "jamesbond", "pumpkins", "Iloveyou2", "amsterdam", "24682468", "christopher"
];
